apiVersion: v1
kind: Service
metadata:
  name: classifier-using-js-service
spec:
  selector:
    app: classifier-using-js
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
